import { useEffect, useMemo, useState } from 'react';
import type { Product, Shop, MonthlyCost } from '@/types';
import { COST_FIELDS } from '@/types';
import { createProduct, deleteProduct, fetchDailyMetrics, fetchDailyPromotions, fetchMonthlyCosts, fetchProducts, updateProduct, upsertDailyMetric, upsertDailyPromotion } from '@/lib/db';
import Modal from '@/components/Modal';
import { showToast } from '@/components/Toast';
import { formatCurrency, formatPercent, getQuickRange } from '@/lib/calc';

interface Props { currentShop: Shop | null; shops: Shop[]; setShops: (shops: Shop[]) => void; }
interface Stats { sales: number; refund: number; net: number; orders: number; visitors: number; promo: number; cost: number; profit: number; }
type RangeKey = 'last30Days' | 'thisMonth' | 'lastMonth' | 'thisNaturalYear';
const ranges: Array<{ key: RangeKey; label: string }> = [{ key: 'last30Days', label: '近30天' }, { key: 'thisMonth', label: '本月' }, { key: 'lastMonth', label: '上月' }, { key: 'thisNaturalYear', label: '本年' }];

export default function ProductView({ currentShop, shops }: Props) {
  const [products, setProducts] = useState<Product[]>([]); const [stats, setStats] = useState<Record<string, Stats>>({}); const [loading, setLoading] = useState(true);
  const [rangeKey, setRangeKey] = useState<RangeKey>('thisMonth'); const [query, setQuery] = useState(''); const [status, setStatus] = useState('all'); const [category, setCategory] = useState('all'); const [sort, setSort] = useState<'sales' | 'profit' | 'refund' | 'roas'>('sales');
  const [editing, setEditing] = useState<Product | null>(null); const [creating, setCreating] = useState(false); const [recording, setRecording] = useState<Product | null>(null);
  const range = useMemo(() => getQuickRange(rangeKey), [rangeKey]);

  const load = async () => {
    const target = currentShop ? [currentShop] : shops; if (!target.length) { setProducts([]); setLoading(false); return; } setLoading(true);
    try {
      const list = (await Promise.all(target.map((s) => fetchProducts(s.id)))).flat(); const next: Record<string, Stats> = {};
      await Promise.all(list.map(async (p) => {
        const [metrics, promotions, costs] = await Promise.all([fetchDailyMetrics(p.shopId, p.id, range.start, range.end), fetchDailyPromotions(p.shopId, p.id, range.start, range.end), fetchMonthlyCosts(p.shopId, p.id, Number(range.start.slice(0, 4)), 1, Number(range.end.slice(0, 4)), 12)]);
        const sales = metrics.reduce((v, m) => v + Number(m.salesAmount || 0), 0); const refund = metrics.reduce((v, m) => v + Number(m.refundAmount || 0), 0); const orders = metrics.reduce((v, m) => v + Number(m.orderCount || 0), 0); const visitors = metrics.reduce((v, m) => v + Number(m.visitorCount || 0), 0); const promo = metrics.length ? metrics.reduce((v, m) => v + Number(m.promotionCost || 0), 0) : promotions.reduce((v, m) => v + Number(m.total || 0), 0); const net = sales - refund; const shop = shops.find((s) => s.id === p.shopId); const productCost = p.unitCost != null ? orders * p.unitCost : net * Number(shop?.defaultCostRate || 0) / 100; const otherCost = costs.reduce((v, c) => v + COST_FIELDS.filter((f) => f.key !== 'productCost').reduce((x, f) => x + Number(c[f.key as keyof MonthlyCost] || 0), 0), 0); const cost = productCost + otherCost;
        next[p.id] = { sales, refund, net, orders, visitors, promo, cost, profit: net - cost - promo };
      })); setProducts(list); setStats(next);
    } catch (e: any) { showToast(e.message || '加载产品数据失败', 'error'); } finally { setLoading(false); }
  };
  useEffect(() => { load(); }, [currentShop, shops, range.start, range.end]);

  const categories = useMemo(() => Array.from(new Set(products.map((p) => p.category).filter(Boolean))) as string[], [products]);
  const visible = useMemo(() => products.filter((p) => { const s = stats[p.id]; if (!s) return false; return (status === 'all' || p.status === status) && (category === 'all' || p.category === category) && (!query || `${p.name} ${p.sku || ''}`.toLowerCase().includes(query.toLowerCase())); }).sort((a, b) => { const x = stats[a.id]; const y = stats[b.id]; if (sort === 'profit') return y.profit - x.profit; if (sort === 'refund') return y.refund / Math.max(y.sales, 1) - x.refund / Math.max(x.sales, 1); if (sort === 'roas') return y.net / Math.max(y.promo, 1) - x.net / Math.max(x.promo, 1); return y.sales - x.sales; }), [products, stats, status, category, query, sort]);
  const summary = visible.reduce((a, p) => { const s = stats[p.id]; a.net += s.net; a.profit += s.profit; a.refund += s.refund; a.promo += s.promo; return a; }, { net: 0, profit: 0, refund: 0, promo: 0 });
  const remove = async (p: Product) => { if (!confirm(`确定删除商品“${p.name}”吗？`)) return; try { await deleteProduct(p.id); showToast('已删除', 'success'); load(); } catch (e: any) { showToast(e.message || '删除失败', 'error'); } };

  if (!shops.length) return <div className="card p-12 text-center text-slate-500">请先添加店铺，再管理商品。</div>;
  return <div className="space-y-4">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="text-xl font-semibold">产品中心</h2><p className="text-sm text-slate-500 mt-1">经营分析与投放决策</p></div><button className="btn-primary" onClick={() => setCreating(true)}>+ 添加商品</button></div>
    <div className="card p-3 flex flex-wrap gap-2 items-center"><div className="flex gap-1">{ranges.map((r) => <button key={r.key} onClick={() => setRangeKey(r.key)} className={`px-3 py-1.5 text-sm rounded ${rangeKey === r.key ? 'bg-primary-600 text-white' : 'bg-slate-100 text-slate-600'}`}>{r.label}</button>)}</div><input className="input max-w-xs" placeholder="搜索商品或 SKU" value={query} onChange={(e) => setQuery(e.target.value)} /><select className="input w-auto" value={status} onChange={(e) => setStatus(e.target.value)}><option value="all">全部状态</option><option value="active">在售</option><option value="inactive">下架</option><option value="discontinued">停售</option></select><select className="input w-auto" value={category} onChange={(e) => setCategory(e.target.value)}><option value="all">全部分类</option>{categories.map((c) => <option key={c} value={c}>{c}</option>)}</select></div>
    <div className="grid grid-cols-2 md:grid-cols-5 gap-3">{[['商品数', visible.length], ['净销售额', formatCurrency(summary.net)], ['利润', formatCurrency(summary.profit)], ['退款金额', formatCurrency(summary.refund)], ['ROAS', summary.promo ? (summary.net / summary.promo).toFixed(2) : '—']].map(([label, value]) => <div className="card p-3" key={String(label)}><div className="text-xs text-slate-500">{label}</div><div className="text-lg font-semibold mt-1">{value}</div></div>)}</div>
    <div className="card overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left text-xs text-slate-500 border-b"><th className="p-3">商品</th><th className="p-3">销售/净销售</th><th className="p-3">订单/转化</th><th className="p-3">退款率</th><th className="p-3">推广/ROAS</th><th className="p-3">利润/利润率</th><th className="p-3">操作</th></tr></thead><tbody>{!loading && visible.map((p) => { const s = stats[p.id]; const refundRate = s.sales ? s.refund / s.sales * 100 : 0; const conversion = s.visitors ? s.orders / s.visitors * 100 : 0; const roas = s.promo ? s.net / s.promo : 0; const margin = s.net ? s.profit / s.net * 100 : 0; return <tr key={p.id} className="border-b last:border-0"><td className="p-3"><div className="font-medium">{p.name}</div><div className="text-xs text-slate-400">{p.sku || '无 SKU'} · {p.category || '未分类'}</div></td><td className="p-3">{formatCurrency(s.sales)}<div className="text-xs text-slate-400">净 {formatCurrency(s.net)}</div></td><td className="p-3">{s.orders}<div className="text-xs text-slate-400">{formatPercent(conversion)}</div></td><td className={`p-3 ${refundRate >= 12 ? 'text-red-500' : ''}`}>{formatPercent(refundRate)}</td><td className="p-3">{formatCurrency(s.promo)}<div className="text-xs text-slate-400">{roas ? roas.toFixed(2) : '—'}</div></td><td className={`p-3 ${s.profit < 0 ? 'text-red-500' : 'text-emerald-600'}`}>{formatCurrency(s.profit)}<div className="text-xs">{formatPercent(margin)}</div></td><td className="p-3 whitespace-nowrap"><button className="btn-primary text-xs mr-1" onClick={() => setRecording(p)}>录入数据</button><button className="btn-secondary text-xs mr-1" onClick={() => setEditing(p)}>编辑</button><button className="btn-danger text-xs" onClick={() => remove(p)}>删除</button></td></tr>; })}</tbody></table>{loading && <div className="p-10 text-center text-slate-400">加载中...</div>}{!loading && !visible.length && <div className="p-10 text-center text-slate-400">没有符合条件的商品</div>}</div>
    {creating && currentShop && <ProductEditor product={null} shopId={currentShop.id} onClose={() => setCreating(false)} onSaved={() => { setCreating(false); load(); }} />}{editing && <ProductEditor product={editing} shopId={editing.shopId} onClose={() => setEditing(null)} onSaved={() => { setEditing(null); load(); }} />}{recording && <ProductDataEditor product={recording} onClose={() => setRecording(null)} onSaved={() => { setRecording(null); load(); }} />}
  </div>;
}

function ProductEditor({ product, shopId, onClose, onSaved }: { product: Product | null; shopId: string; onClose: () => void; onSaved: () => void }) {
  const [name, setName] = useState(product?.name || ''); const [sku, setSku] = useState(product?.sku || ''); const [category, setCategory] = useState(product?.category || ''); const [price, setPrice] = useState(product?.salePrice?.toString() || ''); const [cost, setCost] = useState(product?.unitCost?.toString() || ''); const [margin, setMargin] = useState(product?.targetMargin?.toString() || ''); const [tags, setTags] = useState((product?.tags || []).join(', ')); const [status, setStatus] = useState<Product['status']>(product?.status || 'active'); const [saving, setSaving] = useState(false);
  const save = async () => { if (!name.trim()) { showToast('请输入商品名称', 'warning'); return; } setSaving(true); try { const input = { name: name.trim(), sku: sku.trim(), category: category.trim(), salePrice: price === '' ? undefined : Number(price), unitCost: cost === '' ? undefined : Number(cost), targetMargin: margin === '' ? undefined : Number(margin), tags: tags.split(',').map((v) => v.trim()).filter(Boolean), status }; if (product) await updateProduct(product.id, input); else await createProduct({ ...input, sortOrder: 0, shopId }); showToast('已保存', 'success'); onSaved(); } catch (e: any) { showToast(e.message || '保存失败', 'error'); } finally { setSaving(false); } };
  return <Modal open onClose={onClose} title={product ? '编辑商品' : '添加商品'} footer={<><button className="btn-secondary" onClick={onClose}>取消</button><button className="btn-primary" disabled={saving} onClick={save}>{saving ? '保存中...' : '保存'}</button></>}><div className="space-y-3"><div><label className="label">商品名称 *</label><input className="input" value={name} onChange={(e) => setName(e.target.value)} /></div><div className="grid grid-cols-2 gap-3"><div><label className="label">SKU</label><input className="input" value={sku} onChange={(e) => setSku(e.target.value)} /></div><div><label className="label">分类</label><input className="input" value={category} onChange={(e) => setCategory(e.target.value)} /></div><div><label className="label">售价</label><input type="number" min="0" className="input" value={price} onChange={(e) => setPrice(e.target.value)} /></div><div><label className="label">单位成本</label><input type="number" min="0" className="input" value={cost} onChange={(e) => setCost(e.target.value)} /></div><div><label className="label">目标毛利率 (%)</label><input type="number" min="0" max="100" className="input" value={margin} onChange={(e) => setMargin(e.target.value)} /></div><div><label className="label">标签</label><input className="input" value={tags} onChange={(e) => setTags(e.target.value)} /></div></div><div><label className="label">状态</label><select className="input" value={status} onChange={(e) => setStatus(e.target.value as Product['status'])}><option value="active">在售</option><option value="inactive">下架</option><option value="discontinued">停售</option></select></div></div></Modal>;
}

function ProductDataEditor({ product, onClose, onSaved }: { product: Product; onClose: () => void; onSaved: () => void }) {
  const [date, setDate] = useState(new Date().toISOString().slice(0, 10)); const [sales, setSales] = useState(''); const [orders, setOrders] = useState(''); const [refund, setRefund] = useState(''); const [visitors, setVisitors] = useState(''); const [promo, setPromo] = useState(''); const [saving, setSaving] = useState(false);
  const save = async () => { setSaving(true); try { const promotion = Number(promo) || 0; await upsertDailyMetric({ shopId: product.shopId, productId: product.id, date, salesAmount: Number(sales) || 0, orderCount: Number(orders) || 0, refundAmount: Number(refund) || 0, visitorCount: Number(visitors) || 0, promotionCost: promotion, dataSource: 'manual' }); await upsertDailyPromotion({ shopId: product.shopId, productId: product.id, date, total: promotion, isTotalOverridden: true, dataSource: 'manual' }); showToast('经营数据已保存', 'success'); onSaved(); } catch (e: any) { showToast(e.message || '保存经营数据失败', 'error'); } finally { setSaving(false); } };
  return <Modal open onClose={onClose} title={`录入经营数据 · ${product.name}`} footer={<><button className="btn-secondary" onClick={onClose}>取消</button><button className="btn-primary" disabled={saving} onClick={save}>{saving ? '保存中...' : '保存数据'}</button></>}><div className="space-y-3"><div><label className="label">统计日期 *</label><input type="date" className="input" value={date} onChange={(e) => setDate(e.target.value)} /></div><div className="grid grid-cols-2 gap-3"><div><label className="label">销售额</label><input type="number" min="0" className="input" value={sales} onChange={(e) => setSales(e.target.value)} /></div><div><label className="label">订单数</label><input type="number" min="0" className="input" value={orders} onChange={(e) => setOrders(e.target.value)} /></div><div><label className="label">退款金额</label><input type="number" min="0" className="input" value={refund} onChange={(e) => setRefund(e.target.value)} /></div><div><label className="label">访客数</label><input type="number" min="0" className="input" value={visitors} onChange={(e) => setVisitors(e.target.value)} /></div><div className="col-span-2"><label className="label">推广费用</label><input type="number" min="0" className="input" value={promo} onChange={(e) => setPromo(e.target.value)} /></div></div><p className="text-xs text-slate-500">这些数据按日期保存；同一商品同一天再次保存会更新原记录。退款率、转化率、ROAS 和利润会根据日期范围自动累计。</p></div></Modal>;
}
